export const AllWorks = [
    {
        id: 1,
        image: "/img/travel-journal.png",
        title: "Travel Journal",
        subTitle: 'Scrimba React JS challenge',
        githubURL: "https://github.com/Jay035/travel-journal",
        demoURL: "https://jay035.github.io/travel-journal/",
        imagePosition: "object-center",
    },
    {
        id: 2,
        image: "/img/meme-generator.png",
        title: "Meme Generator",
        subTitle: 'Scrimba react course challenge',
        githubURL: "https://github.com/Jay035/meme-generator",
        demoURL: "https://jay035.github.io/meme-generator/",
        imagePosition: "object-center",
    },
    {
        id: 3,
        image: "/img/portfolio.png",
        title: "Portfolio",
        subTitle: 'Personal project',
        githubURL: "https://github.com/Jay035/portfolio",
        demoURL: "https://jay035.github.io/portfolio/",
        imagePosition: "object-left",
    },
    {
        id: 4,
        image: "/img/interactive-rating.jpg",
        title: "Interactive Rating Component",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Interactive-rating-component",
        demoURL: "https://jay035.github.io/Interactive-rating-component/",
        imagePosition: "object-center",
    },
    {
        id: 5,
        image: "/img/advice-generator.jpg",
        title: "Advice Generator",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Advice-generator",
        demoURL: "https://jay035.github.io/Advice-generator/",
        imagePosition: "object-center"
    },
    {
        id: 6,
        image: "/img/todo-app.jpg",
        title: "Todo app",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/todo-app",
        demoURL: "https://jay035.github.io/todo-app/",
        imagePosition: "object-center",
    },
    {
        id: 7,
        image: "/img/ecommerce.jpg",
        title: "ECommerce product page",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/ecommerce-product-page",
        demoURL: "https://jay035.github.io/ecommerce-product-page/",
        imagePosition: "object-[40%]",
    },
    {
        id: 8,
        image: "/img/calculator.jpg",
        title: "Calculator app",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Calculator-app",
        demoURL: "https://jay035.github.io/Calculator/",
        imagePosition: "object-center",
    },
    {
        id: 9,
        image: "/img/social-media-dashboard.jpg",
        title: "Social Media Dashboard",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/social-media-dashboard-with-theme-switcher-master",
        demoURL: "https://jay035.github.io/social-media-dashboard-with-theme-switcher-master/",
        imagePosition: "object-center",
    },
    {
        id: 10,
        image: "/img/launch-countdown.jpg",
        title: "Launch countdown timer",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/launch-countdown-timer-main",
        demoURL: "https://jay035.github.io/launch-countdown-timer-main/",
        imagePosition: "object-center",
    },
    {
        id: 11,
        image: "/img/intro-section.jpg",
        title: "Intro Section",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/intro-section-with-dropdown-navigation",
        demoURL: "https://jay035.github.io/intro-section-with-dropdown-navigation/",
        imagePosition: "object-left",
    },
    {
        id: 13,
        image: "/img/HNG_Resume.png",
        title: "Resume",
        subTitle: 'Task by HNG internship',
        githubURL: "https://github.com/Jay035/Resume",
        demoURL: "https://jay035.github.io/HNG%20Resume/",
        imagePosition: "object-[20%]",
    },
    {
        id: 20,
        image: "/img/fylo-landing-page.jpg",
        title: "Fylo landing page",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/fylo-dark-theme-landing-page-master",
        demoURL: "https://jay035.github.io/fylo-dark-theme-landing-page-master/",
        imagePosition: "object-center",
    },
    {
        id: 21,
        image: "/img/counter.png",
        title: "Counter",
        subTitle: 'Task by SideHustle internship',
        githubURL: "https://github.com/Jay035/Javascript-projects/tree/main/Counter",
        demoURL: "https://jay035.github.io/Javascript%20counter/",
        imagePosition: "object-center",
    },
    {
        id: 22,
        image: "/img/dashboard.png",
        title: "ECare Doctor's dashboard",
        subTitle: 'Task by ZURI Internship',
        githubURL: "https://github.com/Jay035/ECare/tree/main",
        demoURL: "https://jay035.github.io/ECare/",
        imagePosition: "object-left",
    },
    {
        id: 23,
        image: "/img/social-proof.jpg",
        title: "Social proof section",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/social-proof-section-master",
        demoURL: "https://jay035.github.io/social-proof-section-master/",
        imagePosition: "object-[35%]",
    },
    {
        id: 24,
        image: "/img/chat-app-illustration.jpg",
        title: "Chat app Illustration",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/chat-app-css-illustration-master",
        demoURL: "https://jay035.github.io/chat-app-css-illustration-master/",
        imagePosition: "object-center",
    },
    {
        id: 25,
        image: "/img/3-column-card.jpg",
        title: "3 Column card",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/3-column-preview-card-component-main",
        demoURL: "https://jay035.github.io/3-column-preview-card/",
        imagePosition: "object-center",
    },
]

export const ReactJSWorks = [
    {
        id: 1,
        image: "/img/travel-journal.png",
        title: "Travel Journal",
        subTitle: 'Scrimba React JS challenge',
        githubURL: "https://github.com/Jay035/travel-journal",
        demoURL: "https://jay035.github.io/travel-journal/",
        imagePosition: "object-center",
        // description: "A react project from @scrimba react course",
        // class: "html css javascript react"
    },
    {
        id: 2,
        image: "/img/meme-generator.png",
        title: "Meme Generator",
        subTitle: 'Scrimba react course challenge',
        githubURL: "https://github.com/Jay035/meme-generator",
        demoURL: "https://jay035.github.io/meme-generator/",
        imagePosition: "object-center",
    },
    {
        id: 3,
        image: "/img/portfolio.png",
        title: "Portfolio",
        subTitle: 'Personal project',
        githubURL: "https://github.com/Jay035/portfolio",
        demoURL: "https://jay035.github.io/portfolio/",
        imagePosition: "object-left",
    },
    {
        id: 4,
        image: "/img/interactive-rating.jpg",
        title: "Interactive Rating Component",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Interactive-rating-component",
        demoURL: "https://jay035.github.io/Interactive-rating-component/",
        imagePosition: "object-center",
    },
]

export const VanillaJSWorks = [
    {
        id: 1,
        image: "/img/advice-generator.jpg",
        title: "Advice Generator",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Advice-generator",
        demoURL: "https://jay035.github.io/Advice-generator/",
        imagePosition: "object-center"
    },
    {
        id: 2,
        image: "/img/todo-app.jpg",
        title: "Todo app",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/todo-app",
        demoURL: "https://jay035.github.io/todo-app/",
        imagePosition: "object-center",
    },
    {
        id: 3,
        image: "/img/ecommerce.jpg",
        title: "ECommerce product page",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/ecommerce-product-page",
        demoURL: "https://jay035.github.io/ecommerce-product-page/",
        imagePosition: "object-[40%]",
    },
    {
        id: 4,
        image: "/img/calculator.jpg",
        title: "Calculator app",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Calculator-app",
        demoURL: "https://jay035.github.io/Calculator/",
        imagePosition: "object-center",
    },
    {
        id: 5,
        image: "/img/social-media-dashboard.jpg",
        title: "Social Media Dashboard",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/social-media-dashboard-with-theme-switcher-master",
        demoURL: "https://jay035.github.io/social-media-dashboard-with-theme-switcher-master/",
        imagePosition: "object-center",
    },
    {
        id: 6,
        image: "/img/launch-countdown.jpg",
        title: "Launch countdown timer",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/launch-countdown-timer-main",
        demoURL: "https://jay035.github.io/launch-countdown-timer-main/",
        imagePosition: "object-center",
    },
    {
        id: 7,
        image: "/img/intro-section.jpg",
        title: "Intro Section",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/intro-section-with-dropdown-navigation",
        demoURL: "https://jay035.github.io/intro-section-with-dropdown-navigation/",
        imagePosition: "object-left",
    },
]

export const VanillaCSSWorks = [
    {
        id: 1,
        image: "/img/intro-section.jpg",
        title: "Intro Section",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/intro-section-with-dropdown-navigation",
        demoURL: "https://jay035.github.io/intro-section-with-dropdown-navigation/",
        imagePosition: "object-left",
    },
    {
        id: 2,
        image: "/img/HNG_Resume.png",
        title: "Resume",
        subTitle: 'Task by HNG internship',
        githubURL: "https://github.com/Jay035/Resume",
        demoURL: "https://jay035.github.io/HNG%20Resume/",
        imagePosition: "object-[20%]",
    },
    {
        id: 3,
        image: "/img/advice-generator.jpg",
        title: "Advice Generator",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Advice-generator",
        demoURL: "https://jay035.github.io/Advice-generator/",
        imagePosition: "object-center"
    },
    {
        id: 4,
        image: "/img/ecommerce.jpg",
        title: "ECommerce product page",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/ecommerce-product-page",
        demoURL: "https://jay035.github.io/ecommerce-product-page/",
        imagePosition: "object-[40%]",
    },
    {
        id: 5,
        image: "/img/launch-countdown.jpg",
        title: "Launch countdown timer",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/launch-countdown-timer-main",
        demoURL: "https://jay035.github.io/launch-countdown-timer-main/",
        imagePosition: "object-center",
    },
    {
        id: 6,
        image: "/img/todo-app.jpg",
        title: "Todo app",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/todo-app",
        demoURL: "https://jay035.github.io/todo-app/",
        imagePosition: "object-center",
    },
    {
        id: 7,
        image: "/img/calculator.jpg",
        title: "Calculator app",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Calculator-app",
        demoURL: "https://jay035.github.io/Calculator/",
        imagePosition: "object-center",
    },
    {
        id: 8,
        image: "/img/social-media-dashboard.jpg",
        title: "Social Media Dashboard",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/social-media-dashboard-with-theme-switcher-master",
        demoURL: "https://jay035.github.io/social-media-dashboard-with-theme-switcher-master/",
        imagePosition: "object-center",
    },
    {
        id: 9,
        image: "/img/fylo-landing-page.jpg",
        title: "Fylo landing page",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/fylo-dark-theme-landing-page-master",
        demoURL: "https://jay035.github.io/fylo-dark-theme-landing-page-master/",
        imagePosition: "object-center",
    },
    {
        id: 10,
        image: "/img/counter.png",
        title: "Counter",
        subTitle: 'Task by SideHustle internship',
        githubURL: "https://github.com/Jay035/Javascript-projects/tree/main/Counter",
        demoURL: "https://jay035.github.io/Javascript%20counter/",
        imagePosition: "object-center",
    },
    {
        id: 11,
        image: "/img/dashboard.png",
        title: "ECare Doctor's dashboard",
        subTitle: 'Task by ZURI Internship',
        githubURL: "https://github.com/Jay035/ECare/tree/main",
        demoURL: "https://jay035.github.io/ECare/",
        imagePosition: "object-left",
    },
    {
        id: 12,
        image: "/img/social-proof.jpg",
        title: "Social proof section",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/social-proof-section-master",
        demoURL: "https://jay035.github.io/social-proof-section-master/",
        imagePosition: "object-[35%]",
    },
    {
        id: 13,
        image: "/img/chat-app-illustration.jpg",
        title: "Chat app Illustration",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/chat-app-css-illustration-master",
        demoURL: "https://jay035.github.io/chat-app-css-illustration-master/",
        imagePosition: "object-center",
    },
    {
        id: 14,
        image: "/img/3-column-card.jpg",
        title: "3 Column card",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/3-column-preview-card-component-main",
        demoURL: "https://jay035.github.io/3-column-preview-card/",
        imagePosition: "object-center",
    },
    
]

export const HTMLWorks = [
    {
        id: 1,
        image: "/img/intro-section.jpg",
        title: "Intro Section",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/intro-section-with-dropdown-navigation",
        demoURL: "https://jay035.github.io/intro-section-with-dropdown-navigation/",
        imagePosition: "object-left",
    },
    {
        id: 2,
        image: "/img/HNG_Resume.png",
        title: "Resume",
        subTitle: 'Task by HNG internship',
        githubURL: "https://github.com/Jay035/Resume",
        demoURL: "https://jay035.github.io/HNG%20Resume/",
        imagePosition: "object-[20%]",
    },
    {
        id: 3,
        image: "/img/advice-generator.jpg",
        title: "Advice Generator",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Advice-generator",
        demoURL: "https://jay035.github.io/Advice-generator/",
        imagePosition: "object-center"
    },
    {
        id: 4,
        image: "/img/ecommerce.jpg",
        title: "ECommerce product page",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/ecommerce-product-page",
        demoURL: "https://jay035.github.io/ecommerce-product-page/",
        imagePosition: "object-[40%]",
    },
    {
        id: 5,
        image: "/img/sunnyside-landing-page.jpg",
        title: "Sunnyside landing page",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/sunnyside-agency-landing-page",
        demoURL: "https://jay035.github.io/sunnyside-agency-landing-page/",
        imagePosition: "object-center",
    },
    {
        id: 6,
        image: "/img/launch-countdown.jpg",
        title: "Launch countdown timer",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/launch-countdown-timer-main",
        demoURL: "https://jay035.github.io/launch-countdown-timer-main/",
        imagePosition: "object-center",
    },
    {
        id: 7,
        image: "/img/todo-app.jpg",
        title: "Todo app",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/todo-app",
        demoURL: "https://jay035.github.io/todo-app/",
        imagePosition: "object-center",
    },
    {
        id: 8,
        image: "/img/calculator.jpg",
        title: "Calculator app",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Calculator-app",
        demoURL: "https://jay035.github.io/Calculator/",
        imagePosition: "object-center",
    },
    {
        id: 9,
        image: "/img/social-media-dashboard.jpg",
        title: "Social Media Dashboard",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/social-media-dashboard-with-theme-switcher-master",
        demoURL: "https://jay035.github.io/social-media-dashboard-with-theme-switcher-master/",
        imagePosition: "object-center",
    },
    {
        id: 10,
        image: "/img/fylo-landing-page.jpg",
        title: "Fylo landing page",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/fylo-dark-theme-landing-page-master",
        demoURL: "https://jay035.github.io/fylo-dark-theme-landing-page-master/",
        imagePosition: "object-center",
    },
    {
        id: 11,
        image: "/img/counter.png",
        title: "Counter",
        subTitle: 'Task by SideHustle internship',
        githubURL: "https://github.com/Jay035/Javascript-projects/tree/main/Counter",
        demoURL: "https://jay035.github.io/Javascript%20counter/",
        imagePosition: "object-center",
    },
    {
        id: 12,
        image: "/img/dashboard.png",
        title: "ECare Doctor's dashboard",
        subTitle: 'Task by ZURI Internship',
        githubURL: "https://github.com/Jay035/ECare/tree/main",
        demoURL: "https://jay035.github.io/ECare/",
        imagePosition: "object-left",
    },
    {
        id: 13,
        image: "/img/social-proof.jpg",
        title: "Social proof section",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/social-proof-section-master",
        demoURL: "https://jay035.github.io/social-proof-section-master/",
        imagePosition: "object-[35%]",
    },
    {
        id: 14,
        image: "/img/chat-app-illustration.jpg",
        title: "Chat app Illustration",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/chat-app-css-illustration-master",
        demoURL: "https://jay035.github.io/chat-app-css-illustration-master/",
        imagePosition: "object-center",
    },
    {
        id: 15,
        image: "/img/3-column-card.jpg",
        title: "3 Column card",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/3-column-preview-card-component-main",
        demoURL: "https://jay035.github.io/3-column-preview-card/",
        imagePosition: "object-center",
    },
]

export const TailwindCSSWorks = [
    {
        id: 1,
        image: "/img/portfolio.png",
        title: "Portfolio",
        subTitle: 'Personal project',
        githubURL: "",
        demoURL: "",
        imagePosition: "object-left",
    },
    {
        id: 2,
        image: "/img/sunnyside-landing-page.jpg",
        title: "Sunnyside landing page",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/sunnyside-agency-landing-page",
        demoURL: "https://jay035.github.io/sunnyside-agency-landing-page/",
        imagePosition: "object-center",
    },
]