import travelJournalImg from '../components/assets/travel-journal.png';
import spaceTourismImg from '../components/assets/space-tourism-page.jpg';
import timeTrackingDashboard from '../components/assets/time-tracking-dashboard.png';
import memeGeneratorImg from '../components/assets/meme-generator.png';
import adviceGeneratorImg from '../components/assets/advice-generator.jpg';
import portfolioImg from '../components/assets/portfolio.png';
import calculatorImg from '../components/assets/calculator.jpg';
// import chatImg from '../components/assets/chat-app-illustration.jpg';
// import columnCardImg from '../components/assets/3-column-card.jpg';
// import counterImg from '../components/assets/counter.png';
// import dashboardImg from '../components/assets/dashboard.png';
import ecommerceImg from '../components/assets/ecommerce.jpg';
import fyloLandingPage from '../components/assets/fylo-landing-page.jpg';
// import HNGResumeImg from '../components/assets/HNG_Resume.png';
// import hoadrImg from '../components/assets/hoadr.png';
import interactiveRatingImg from '../components/assets/interactive-rating.jpg';
import introSectionImg from '../components/assets/intro-section.jpg';
import launchCountdownImg from '../components/assets/launch-countdown.jpg';
// import orderSummaryImg from '../components/assets/order-summary-component.jpg';
import socialMediaDashboard from '../components/assets/social-media-dashboard.jpg';
// import socialProofImg from '../components/assets/social-proof.jpg';
import sunnysideLandingpage from '../components/assets/sunnyside-landing-page.jpg';
// import testimonialsPageImg from '../components/assets/testimonials-page.png'
import todoApp from '../components/assets/todo-app.jpg';


export const AllWorks = [
    {
        id: 1,
        image: spaceTourismImg,
        title: "Space Tourism website",
        subTitle: 'A multi-page space tourism website ',
        githubURL: "https://github.com/Jay035/Space-tourism-Multi-page-website",
        demoURL: "https://space-tourism-reactjs-website.netlify.app/",
        imagePosition: "object-center",
    },
    {
        id: 2,
        image: travelJournalImg,
        title: "Travel Journal",
        subTitle: 'Scrimba React JS course challenge',
        githubURL: "https://github.com/Jay035/travel-journal",
        demoURL: "https://jay035.github.io/travel-journal/",
        imagePosition: "object-center",
    },
    {
        id: 3,
        image: memeGeneratorImg,
        title: "Meme Generator",
        subTitle: 'Scrimba React JS course challenge',
        githubURL: "https://github.com/Jay035/meme-generator",
        demoURL: "https://jay035.github.io/meme-generator/",
        imagePosition: "object-center",
    },
    {
        id: 4,
        image: portfolioImg,
        title: "Portfolio",
        subTitle: 'Personal project',
        githubURL: "https://github.com/Jay035/portfolio",
        demoURL: "https://jay035.github.io/portfolio/",
        imagePosition: "object-left",
    },
    {
        id: 5,
        image: timeTrackingDashboard,
        title: "Time Tracking Dashboard",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Time-tracking-dashboard",
        demoURL: "https://jay035.github.io/Time-tracking-dashboard/",
        imagePosition: "object-[30%]",
    },
    {
        id: 6,
        image: interactiveRatingImg,
        title: "Interactive Rating Component",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Interactive-rating-component",
        demoURL: "https://jay035.github.io/Interactive-rating-component/",
        imagePosition: "object-center",
    },
    {
        id: 7,
        image: adviceGeneratorImg,
        title: "Advice Generator",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Advice-generator",
        demoURL: "https://jay035.github.io/Advice-generator/",
        imagePosition: "object-center"
    },
    {
        id: 8,
        image: todoApp,
        title: "Todo app",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/todo-app",
        demoURL: "https://jay035.github.io/todo-app/",
        imagePosition: "object-center",
    },
    {
        id: 9,
        image: ecommerceImg,
        title: "ECommerce product page",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/ecommerce-product-page",
        demoURL: "https://jay035.github.io/ecommerce-product-page/",
        imagePosition: "object-[40%]",
    },
    {
        id: 10,
        image: calculatorImg,
        title: "Calculator app",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Calculator-app",
        demoURL: "https://jay035.github.io/Calculator/",
        imagePosition: "object-center",
    },
    {
        id: 11,
        image: socialMediaDashboard,
        title: "Social Media Dashboard",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/social-media-dashboard-with-theme-switcher-master",
        demoURL: "https://jay035.github.io/social-media-dashboard-with-theme-switcher-master/",
        imagePosition: "object-center",
    },
    {
        id: 12,
        image: launchCountdownImg,
        title: "Launch countdown timer",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/launch-countdown-timer-main",
        demoURL: "https://jay035.github.io/launch-countdown-timer-main/",
        imagePosition: "object-center",
    },
    {
        id: 13,
        image: introSectionImg,
        title: "Intro Section",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/intro-section-with-dropdown-navigation",
        demoURL: "https://jay035.github.io/intro-section-with-dropdown-navigation/",
        imagePosition: "object-left",
    },
    // {
    //     id: 14,
    //     image: HNGResumeImg,
    //     title: "Resume",
    //     subTitle: 'Task by HNG internship',
    //     githubURL: "https://github.com/Jay035/Resume",
    //     demoURL: "https://jay035.github.io/HNG%20Resume/",
    //     imagePosition: "object-[20%]",
    // },
    {
        id: 14,
        image: fyloLandingPage,
        title: "Fylo landing page",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/fylo-dark-theme-landing-page-master",
        demoURL: "https://jay035.github.io/fylo-dark-theme-landing-page-master/",
        imagePosition: "object-center",
    },
    // {
    //     id: 16,
    //     image: counterImg,
    //     title: "Counter",
    //     subTitle: 'Task by SideHustle internship',
    //     githubURL: "https://github.com/Jay035/Javascript-projects/tree/main/Counter",
    //     demoURL: "https://jay035.github.io/Javascript%20counter/",
    //     imagePosition: "object-center",
    // },
    // {
    //     id: 17,
    //     image: dashboardImg,
    //     title: "ECare Doctor's dashboard",
    //     subTitle: 'Task by ZURI Internship',
    //     githubURL: "https://github.com/Jay035/ECare/tree/main",
    //     demoURL: "https://jay035.github.io/ECare/",
    //     imagePosition: "object-left",
    // },
    // {
    //     id: 18,
    //     image: socialProofImg,
    //     title: "Social proof section",
    //     subTitle: 'Frontendmentor challenge',
    //     githubURL: "https://github.com/Jay035/social-proof-section",
    //     demoURL: "https://jay035.github.io/social-proof-section/",
    //     imagePosition: "object-[35%]",
    // },
    // {
    //     id: 19,
    //     image: chatImg,
    //     title: "Chat app Illustration",
    //     subTitle: 'Frontendmentor challenge',
    //     githubURL: "https://github.com/Jay035/chat-app-css-illustration",
    //     demoURL: "https://jay035.github.io/chat-app-css-illustration/",
    //     imagePosition: "object-center",
    // },
    // {
    //     id: 20,
    //     image: columnCardImg,
    //     title: "3 Column card",
    //     subTitle: 'Frontendmentor challenge',
    //     githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/3-column-preview-card-component-main",
    //     demoURL: "https://jay035.github.io/3-column-preview-card/",
    //     imagePosition: "object-center",
    // },
]

export const ReactJSWorks = [
    {
        id: 1,
        image: spaceTourismImg,
        title: "Space Tourism website",
        subTitle: 'FrontendMentor challenge',
        githubURL: "https://github.com/Jay035/Space-tourism-Multi-page-website",
        demoURL: "https://space-tourism-reactjs-website.netlify.app/",
        imagePosition: "object-center",
    },
    {
        id: 2,
        image: travelJournalImg,
        title: "Travel Journal",
        subTitle: 'Scrimba React JS challenge',
        githubURL: "https://github.com/Jay035/travel-journal",
        demoURL: "https://jay035.github.io/travel-journal/",
        imagePosition: "object-center",
        // description: "A react project from @scrimba react course",
        // class: "html css javascript react"
    },
    {
        id: 3,
        image: memeGeneratorImg,
        title: "Meme Generator",
        subTitle: 'Scrimba react course challenge',
        githubURL: "https://github.com/Jay035/meme-generator",
        demoURL: "https://jay035.github.io/meme-generator/",
        imagePosition: "object-center",
    },
    {
        id: 4,
        image: portfolioImg,
        title: "Portfolio",
        subTitle: 'Personal project',
        githubURL: "https://github.com/Jay035/portfolio",
        demoURL: "https://jay035.github.io/portfolio/",
        imagePosition: "object-left",
    },
    {
        id: 5,
        image: timeTrackingDashboard,
        title: "Time Tracking Dashboard",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Time-tracking-dashboard",
        demoURL: "https://jay035.github.io/Time-tracking-dashboard/",
        imagePosition: "object-left",
    },
    {
        id: 6,
        image: interactiveRatingImg,
        title: "Interactive Rating Component",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Interactive-rating-component",
        demoURL: "https://jay035.github.io/Interactive-rating-component/",
        imagePosition: "object-center",
    },
]

export const VanillaJSWorks = [
    {
        id: 1,
        image: adviceGeneratorImg,
        title: "Advice Generator",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Advice-generator",
        demoURL: "https://jay035.github.io/Advice-generator/",
        imagePosition: "object-center"
    },
    {
        id: 2,
        image: todoApp,
        title: "Todo app",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/todo-app",
        demoURL: "https://jay035.github.io/todo-app/",
        imagePosition: "object-center",
    },
    {
        id: 3,
        image: ecommerceImg,
        title: "ECommerce product page",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/ecommerce-product-page",
        demoURL: "https://jay035.github.io/ecommerce-product-page/",
        imagePosition: "object-[40%]",
    },
    {
        id: 4,
        image: calculatorImg,
        title: "Calculator app",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Calculator-app",
        demoURL: "https://jay035.github.io/Calculator/",
        imagePosition: "object-center",
    },
    {
        id: 5,
        image: socialMediaDashboard,
        title: "Social Media Dashboard",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/social-media-dashboard-with-theme-switcher-master",
        demoURL: "https://jay035.github.io/social-media-dashboard-with-theme-switcher-master/",
        imagePosition: "object-center",
    },
    {
        id: 6,
        image: launchCountdownImg,
        title: "Launch countdown timer",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/launch-countdown-timer-main",
        demoURL: "https://jay035.github.io/launch-countdown-timer-main/",
        imagePosition: "object-center",
    },
    {
        id: 7,
        image: introSectionImg,
        title: "Intro Section",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/intro-section-with-dropdown-navigation",
        demoURL: "https://jay035.github.io/intro-section-with-dropdown-navigation/",
        imagePosition: "object-left",
    },
]

export const VanillaCSSWorks = [
    {
        id: 1,
        image: introSectionImg,
        title: "Intro Section",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/intro-section-with-dropdown-navigation",
        demoURL: "https://jay035.github.io/intro-section-with-dropdown-navigation/",
        imagePosition: "object-left",
    },
    // {
    //     id: 2,
    //     image: HNGResumeImg,
    //     title: "Resume",
    //     subTitle: 'Task by HNG internship',
    //     githubURL: "https://github.com/Jay035/Resume",
    //     demoURL: "https://jay035.github.io/HNG%20Resume/",
    //     imagePosition: "object-[20%]",
    // },
    {
        id: 3,
        image: adviceGeneratorImg,
        title: "Advice Generator",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Advice-generator",
        demoURL: "https://jay035.github.io/Advice-generator/",
        imagePosition: "object-center"
    },
    {
        id: 4,
        image: ecommerceImg,
        title: "ECommerce product page",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/ecommerce-product-page",
        demoURL: "https://jay035.github.io/ecommerce-product-page/",
        imagePosition: "object-[40%]",
    },
    {
        id: 5,
        image: launchCountdownImg,
        title: "Launch countdown timer",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/launch-countdown-timer-main",
        demoURL: "https://jay035.github.io/launch-countdown-timer-main/",
        imagePosition: "object-center",
    },
    {
        id: 6,
        image: todoApp,
        title: "Todo app",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/todo-app",
        demoURL: "https://jay035.github.io/todo-app/",
        imagePosition: "object-center",
    },
    {
        id: 7,
        image: calculatorImg,
        title: "Calculator app",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Calculator-app",
        demoURL: "https://jay035.github.io/Calculator/",
        imagePosition: "object-center",
    },
    {
        id: 8,
        image: socialMediaDashboard,
        title: "Social Media Dashboard",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/social-media-dashboard-with-theme-switcher-master",
        demoURL: "https://jay035.github.io/social-media-dashboard-with-theme-switcher-master/",
        imagePosition: "object-center",
    },
    {
        id: 9,
        image: fyloLandingPage,
        title: "Fylo landing page",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/fylo-dark-theme-landing-page-master",
        demoURL: "https://jay035.github.io/fylo-dark-theme-landing-page-master/",
        imagePosition: "object-center",
    },
    // {
    //     id: 10,
    //     image: counterImg,
    //     title: "Counter",
    //     subTitle: 'Task by SideHustle internship',
    //     githubURL: "https://github.com/Jay035/Javascript-projects/tree/main/Counter",
    //     demoURL: "https://jay035.github.io/Javascript%20counter/",
    //     imagePosition: "object-center",
    // },
    // {
    //     id: 11,
    //     image: dashboardImg,
    //     title: "ECare Doctor's dashboard",
    //     subTitle: 'Task by ZURI Internship',
    //     githubURL: "https://github.com/Jay035/ECare/tree/main",
    //     demoURL: "https://jay035.github.io/ECare/",
    //     imagePosition: "object-left",
    // },
    // {
    //     id: 12,
    //     image: socialProofImg,
    //     title: "Social proof section",
    //     subTitle: 'Frontendmentor challenge',
    //     githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/social-proof-section-master",
    //     demoURL: "https://jay035.github.io/social-proof-section-master/",
    //     imagePosition: "object-[35%]",
    // },
    // {
    //     id: 13,
    //     image: chatImg,
    //     title: "Chat app Illustration",
    //     subTitle: 'Frontendmentor challenge',
    //     githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/chat-app-css-illustration-master",
    //     demoURL: "https://jay035.github.io/chat-app-css-illustration-master/",
    //     imagePosition: "object-center",
    // },
    // {
    //     id: 14,
    //     image: columnCardImg,
    //     title: "3 Column card",
    //     subTitle: 'Frontendmentor challenge',
    //     githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/3-column-preview-card-component-main",
    //     demoURL: "https://jay035.github.io/3-column-preview-card/",
    //     imagePosition: "object-center",
    // },
    
]

export const HTMLWorks = [
    {
        id: 1,
        image: introSectionImg,
        title: "Intro Section",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/intro-section-with-dropdown-navigation",
        demoURL: "https://jay035.github.io/intro-section-with-dropdown-navigation/",
        imagePosition: "object-left",
    },
    // {
    //     id: 2,
    //     image: HNGResumeImg,
    //     title: "Resume",
    //     subTitle: 'Task by HNG internship',
    //     githubURL: "https://github.com/Jay035/Resume",
    //     demoURL: "https://jay035.github.io/HNG%20Resume/",
    //     imagePosition: "object-[20%]",
    // },
    {
        id: 3,
        image: adviceGeneratorImg,
        title: "Advice Generator",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Advice-generator",
        demoURL: "https://jay035.github.io/Advice-generator/",
        imagePosition: "object-center"
    },
    {
        id: 4,
        image: ecommerceImg,
        title: "ECommerce product page",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/ecommerce-product-page",
        demoURL: "https://jay035.github.io/ecommerce-product-page/",
        imagePosition: "object-[40%]",
    },
    {
        id: 5,
        image: sunnysideLandingpage,
        title: "Sunnyside landing page",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/sunnyside-agency-landing-page",
        demoURL: "https://jay035.github.io/sunnyside-agency-landing-page/",
        imagePosition: "object-center",
    },
    {
        id: 6,
        image: launchCountdownImg,
        title: "Launch countdown timer",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/launch-countdown-timer-main",
        demoURL: "https://jay035.github.io/launch-countdown-timer-main/",
        imagePosition: "object-center",
    },
    {
        id: 7,
        image: todoApp,
        title: "Todo app",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/todo-app",
        demoURL: "https://jay035.github.io/todo-app/",
        imagePosition: "object-center",
    },
    {
        id: 8,
        image: calculatorImg,
        title: "Calculator app",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Calculator-app",
        demoURL: "https://jay035.github.io/Calculator/",
        imagePosition: "object-center",
    },
    {
        id: 9,
        image: socialMediaDashboard,
        title: "Social Media Dashboard",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/social-media-dashboard-with-theme-switcher-master",
        demoURL: "https://jay035.github.io/social-media-dashboard-with-theme-switcher-master/",
        imagePosition: "object-center",
    },
    {
        id: 10,
        image: fyloLandingPage,
        title: "Fylo landing page",
        subTitle: 'Frontendmentor Challenge',
        githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/fylo-dark-theme-landing-page-master",
        demoURL: "https://jay035.github.io/fylo-dark-theme-landing-page-master/",
        imagePosition: "object-center",
    },
    // {
    //     id: 11,
    //     image: counterImg,
    //     title: "Counter",
    //     subTitle: 'Task by SideHustle internship',
    //     githubURL: "https://github.com/Jay035/Javascript-projects/tree/main/Counter",
    //     demoURL: "https://jay035.github.io/Javascript%20counter/",
    //     imagePosition: "object-center",
    // },
    // {
    //     id: 12,
    //     image: dashboardImg,
    //     title: "ECare Doctor's dashboard",
    //     subTitle: 'Task by ZURI Internship',
    //     githubURL: "https://github.com/Jay035/ECare/tree/main",
    //     demoURL: "https://jay035.github.io/ECare/",
    //     imagePosition: "object-left",
    // },
    // {
    //     id: 13,
    //     image: socialProofImg,
    //     title: "Social proof section",
    //     subTitle: 'Frontendmentor challenge',
    //     githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/social-proof-section-master",
    //     demoURL: "https://jay035.github.io/social-proof-section-master/",
    //     imagePosition: "object-[35%]",
    // },
    // {
    //     id: 14,
    //     image: chatImg,
    //     title: "Chat app Illustration",
    //     subTitle: 'Frontendmentor challenge',
    //     githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/chat-app-css-illustration-master",
    //     demoURL: "https://jay035.github.io/chat-app-css-illustration-master/",
    //     imagePosition: "object-center",
    // },
    // {
    //     id: 15,
    //     image: columnCardImg,
    //     title: "3 Column card",
    //     subTitle: 'Frontendmentor challenge',
    //     githubURL: "https://github.com/Jay035/Frontend-mentor/tree/main/3-column-preview-card-component-main",
    //     demoURL: "https://jay035.github.io/3-column-preview-card/",
    //     imagePosition: "object-center",
    // },
]

export const TailwindCSSWorks = [
    {
        id: 1,
        image: portfolioImg,
        title: "Portfolio",
        subTitle: 'Personal project',
        githubURL: "",
        demoURL: "",
        imagePosition: "object-left",
    },
    {
        id: 2,
        image: sunnysideLandingpage,
        title: "Sunnyside landing page",
        subTitle: 'Frontendmentor challenge',
        githubURL: "https://github.com/Jay035/sunnyside-agency-landing-page",
        demoURL: "https://jay035.github.io/sunnyside-agency-landing-page/",
        imagePosition: "object-center",
    },
]